```{r hw6_setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE)
```

# Homework 6 {-}

<center>
**Due Sunday, October 11 at midnight CST on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=37147)**

**Please turn in two PDF documents from class exercises.**

(If you have LaTeX installed, you can knit directly to PDF (preferred method). Otherwise, you can knit to HTML and "Print" the page to save it as a PDF.)
</center>


<br>


## Deliverables {-}

Please turn in exercises from the following class days:

- Topic 17: Applied Mediation Analysis
- Topic 18: Instrumental Variables Analysis

This should be a total of two PDF documents.

<br>


## Primary objectives {-}

The following learning objectives are the primary focus of this assignment:

- **`DSEP1`:** Apply d-separation to block noncausal paths in causal DAGs with and without unobserved variables.
- **`MEDI1`:** Formulate research questions that can be answered via mediation analysis
- **`MEDI2`:** Conduct and interpret results from a mediation analysis
- **`IVAR1`:** Design and evaluate an instrumental variables study in light of the instrumental variables assumptions.
- **`IVAR2`:** Explain how instrument strength and analysis choices affect the results of an instrumental variables analysis


<br>


## Revisiting previous objectives {-}

You can revisit any of the following objectives (excludes `REGR1`, `IPTW1`) by incorporating them within the context of the assignment as below.

```
> **Revisiting objective DESI1:** Enter a response here that demonstrates that you show solid understanding of the DESI1 objective within the context of this assignment.
```

- **`EXCH1`:** Apply the concepts of marginal and conditional exchangeability to answer questions about (hypothetical) data on potential outcomes.
- **`EXCH2`:** Give examples of when marginal and conditional exchangeability would and would not hold in various data contexts.
- **`EXCH3`:** Explain why a direct comparison of the outcomes in the treated and untreated is misleading as an estimate of a causal effect.
- **`DESI1`:** Explain how randomized experiments relate to exchangeability.
- **`DESI2`:** Explain how quasi-experimental and general observational studies relate to exchangeability.
- **`DESI3`:** Compare the strengths and weaknesses of different study designs for answering a research question.
- **`PGRA1`:** Apply the Causal Markov assumption to express the joint distribution of data.
- **`CNCP1`:** Explain how causal and noncausal paths relate to exchangeability and causal effects.
- **`DSEP2`:** Apply strategies to deal with exchangeability problems caused by unobserved variables.
- **`DSEP3`:** Simulate data from a causal DAG under linear and logistic regression SEMs to check d-separation properties through regression modeling and visualization.
- **`DSEP4`:** Explain how d-separation relates to conditional exchangeability.
- **`TVTR1`**: Formulate research questions that can be answered in a time-varying treatment setting.
- **`TVTR2`**: Explain why regression does not generally work in time-varying settings with treatment-confounder feedback using d-separation ideas.

<br>

For the following objectives, you will have opportunities to revise your responses on Homework 5 based on feedback, so do not include these objectives in any revisits you do for this assignmemt.

- **`SENS1`**: Evaluate the sensitivity of findings to data quality and propose appropriate sensitivity analyses for a research investigation
- **`SENS2`**: Conduct and communicate the results of a sensitivity analysis for unmeasured confounding.
- **`DISC1`**: Demonstrate conceptual understanding of causal discovery by reasoning about outputs of the process and by manually conducting it using regression models.
- **`DISC2`**: Use output from causal discovery to enhance a causal analysis as part of a sensitivity analysis.

