```{r project_setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE)
```

# (PART) Project {-}

# Final Project {-}

There are a number of options available for the final project.

Grading scale:

- Not Assessable
- Needs Revisions
- Meets Expectations
- Excellent


<br><br>


## Deliverables {-}

For all projects below, the only deliverable is a "digital artifact" that could be used for the digital capstone showcase. A digital artifact can take any of the following forms:

- A video presentation
- A podcast-style recording
- A set of blog posts

Work with Leslie to determine the most suitable form for your digital artifact, depending on the option you pick.

<br>

**In order to earn an Excellent, your artifact must be presented in a way that is clear and engaging for a student who has only completed STAT 155.** Not every part of the artifact should be easily understood by an introductory student, but they should be able to take away some understanding even from the more advanced material.


<br><br>


## Timeline {-}

You/your group will check in with me in-person over Zoom 3 times over the course of the last 2 weeks of class. **In order to earn a passing grade, you must meet requirements at all deadlines.**

- **Deadline 1:** Choose your final project option, topic, and group by Friday, October 9 at midnight CST (or the corresponding time on Saturday, October 10 if you are in a later time zone). This will not be an in-person check-in, but please submit your responses [on Moodle](https://moodle.macalester.edu/mod/feedback/view.php?id=39190).

<br>

- **Deadline 2:** Monday, October 12 or Tuesday, October 13. Schedule a discussion time with me on [Google Calendar](https://calendar.google.com/calendar/selfsched?sstoken=UUFBWjVpaTNFb2JUfGRlZmF1bHR8ODFhZGU4ZWQ5MjJkOWY2M2Q4YjZhNTgwN2IyMmFlM2Y).
    - Data analysis option: Come prepared to talk about your causal graph, your analysis plan, and exploratory visualizations that you have made.
    - Blog post option: Write 500 words for each post and share with me 24 hours before our meeting so that I can give feedback and discuss with you.
    - Advanced topic option: Come prepared to tell me a bit about what you've learned on your topic. If you were giving a 15 minute presentation on the topic, this should be about the amount of content you would cover in the first 5 minutes.

<br>

- **Deadline 3:** Thursday, October 15 or Friday, October 16. Schedule a discussion time with me on [Google Calendar](https://calendar.google.com/calendar/selfsched?sstoken=UUFBWjVpaTNFb2JUfGRlZmF1bHR8ODFhZGU4ZWQ5MjJkOWY2M2Q4YjZhNTgwN2IyMmFlM2Y).
    - Data analysis option: Come prepared to tell me about the models you've fit and your interpretations. Share a draft of your artifact so far with me 24 hours in advance.
    - Blog post option: Complete full drafts of both posts and share with me 24 hours before our meeting so that I can give feedback and discuss with you.
    - Advanced topic option: Come prepared to tell me more about new material that is the equivalent of the second 5 minutes of a 15 minute presentation. Share a draft of your artifact so far with me 24 hours in advance.

<br>

- **Deadline 4:** Monday, October 19 or Tuesday, October 20. Schedule a discussion time with me on [Google Calendar](https://calendar.google.com/calendar/selfsched?sstoken=UUFBWjVpaTNFb2JUfGRlZmF1bHR8ODFhZGU4ZWQ5MjJkOWY2M2Q4YjZhNTgwN2IyMmFlM2Y).
    - Data analysis option: Come prepared to discuss final points of feedback from the previous meeting (deadline 3). Finalize your artifact draft, and share with me 24 hours in advance.
    - Blog post option: Act on feedback from the previous meeting (deadline 3), and share with me 24 hours before our meeting.
    - Advanced topic option: Come prepared to tell me more about new material that is the equivalent of the last 5 minutes of a 15 minute presentation. Finalize your artifact draft, and share with me 24 hours in advance.

<br>

- **Final deadline:** Friday, October 23. By midnight CST, submit the final version of your digital artifact [on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=39212).
    - We will not have a showcase/presentation day in class, but instead, I look forward to seeing you showcase your work for the department at either of our two departmental capstone unveiling days! (One will be at the end of Module 2 and the other at the end of Module 4.)


<br><br>


## Option 1: Data analysis {-}

**Collaboration:** Groups of up to 3. Individual work is fine.

Perform a causal analysis on a dataset of your choice. To earn an Excellent, the analysis must contain one major component per team member.

Options for major components:

- Regression analysis for causal effect estimation with a sensitivity analysis for unmeasured confounding
- Inverse probability weighting analysis for causal effect estimation with a sensitivity analysis for unmeasured confounding
- Causal discovery as a sensitivity analysis (Information on the `pcalg` R package for causal discovery will be added to our website's appendix.)
- Mediation analysis for causal effect estimation
- Instrumental variables analysis

Resources for finding data:

- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [Harvard Dataverse](https://dataverse.harvard.edu/)
- [Inter-university Consortium for Political and Social Research (ICPSR)](https://www.icpsr.umich.edu/)
- [IPUMS](https://ipums.org/)


<br><br>


## Option 2: Blog posts {-}

**Collaboration:** Individual only.

Write two blog posts explaining causal inference ideas to a general audience. The first post should address one of the three topics below.

- Estrogens and uterine cancer example of selection bias: see [Graphical Structure of Selection Bias], Exercise 3.
- The smoking-birth weight paradox
- Pick any media item that has interested you. Write a reaction to it / an analysis of it from a causal inference perspective.
    - If you're looking to explore some media, the [Casual Inference podcast](https://casualinfer.libsyn.com/) is a fun one!

The second post should be a "tour of causal inference" and lead the reader through all topics covered in our course in a cohesive story.


<br><br>


## Option 3: Learn an advanced topic {-}

**Collaboration:** Groups of up to 3. Individual work is fine.

Dig deeper into course topics or learn a new topic. Examples could include:

- Methods for transportability (generalizability) of effects
- Interference
- Details of methods for time-varying treatments
- Specialized considerations for particular study designs


<br><br>


## Option 4: Other {-}

If none of these options piques your interest, I'm happy to discuss alternatives with you.
